[build]
  command = "npm run build"
  publish = "dist"

# Configure build environment
[build.environment]
  NODE_VERSION = "18"
  VITE_WEATHER_API_KEY = "pqwqiqqTBeljWL7yM8WKwQTgjuKha5Zb"
  VITE_APP_ENV = "production"
  VITE_API_ENDPOINT = "https://api.tomorrow.io/v4"
  VITE_ENABLE_MOCK_DATA = "false"

# Configure redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ignore specific files/folders during build
[build.processing]
  skip_processing = true

# Post-processing configuration
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 